compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
npmAuthToken: "${NODE_AUTH_TOKEN-}"
yarnPath: ../.yarn/releases/yarn-4.1.0.cjs
cacheFolder: "../.yarn/cache"
installStatePath: "./.yarn/integration-test-install-state.gz"
enableInlineBuilds: true